// IANA Timezone options for Location entity.
// Values are IANA timezone IDs; labels present clear, accurate regional names.
const TIMEZONE_LIST = [
  { value: 'America/Anchorage', label: 'Alaska Standard Time (UTC-9:00)' },
  { value: 'America/Puerto_Rico', label: 'Atlantic Standard Time (Puerto Rico, UTC-4:00)' },
  { value: 'Australia/Adelaide', label: 'Australian Central Time (Adelaide, UTC+9:30)' },
  { value: 'Australia/Sydney', label: 'Australian Eastern Time (Sydney, Melbourne, UTC+10:00)' },
  { value: 'Australia/Perth', label: 'Australian Western Standard Time (Perth, UTC+8:00)' },
  { value: 'Asia/Dhaka', label: 'Bangladesh Standard Time (UTC+6:00)' },
  { value: 'America/Sao_Paulo', label: 'Brasilia Time (Sao Paulo, UTC-3:00)' },
  { value: 'Atlantic/Cape_Verde', label: 'Cape Verde Time (UTC-1:00)' },
  { value: 'Europe/Paris', label: 'Central European Time (Paris, Berlin, Rome, UTC+1:00)' },
  { value: 'America/Chicago', label: 'Central Time (US & Canada, UTC-6:00)' },
  { value: 'Asia/Shanghai', label: 'China Standard Time (Beijing, Shanghai, UTC+8:00)' },
  { value: 'Africa/Nairobi', label: 'Eastern African Time (Nairobi, UTC+3:00)' },
  { value: 'Europe/Athens', label: 'Eastern European Time (Athens, Bucharest, UTC+2:00)' },
  { value: 'America/New_York', label: 'Eastern Time (US & Canada, UTC-5:00)' },
  { value: 'Africa/Cairo', label: 'Egypt Standard Time (UTC+2:00)' },
  { value: 'Asia/Dubai', label: 'Gulf Standard Time (Dubai, UTC+4:00)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Standard Time (UTC-10:00)' },
  { value: 'Asia/Kolkata', label: 'India Standard Time (UTC+5:30)' },
  { value: 'Asia/Bangkok', label: 'Indochina Time (Bangkok, Hanoi, UTC+7:00)' },
  { value: 'Asia/Tehran', label: 'Iran Standard Time (UTC+3:30)' },
  { value: 'Asia/Tokyo', label: 'Japan Standard Time (Tokyo, UTC+9:00)' },
  { value: 'Asia/Seoul', label: 'Korea Standard Time (Seoul, UTC+9:00)' },
  { value: 'Pacific/Midway', label: 'Midway Islands Time (UTC-11:00)' },
  { value: 'America/Phoenix', label: 'Mountain Standard Time (Arizona - No DST, UTC-7:00)' },
  { value: 'America/Denver', label: 'Mountain Time (US & Canada, UTC-7:00)' },
  { value: 'America/St_Johns', label: 'Newfoundland Time (UTC-3:30)' },
  { value: 'Pacific/Auckland', label: 'New Zealand Standard Time (Auckland, UTC+12:00)' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (US & Canada, UTC-8:00)' },
  { value: 'Asia/Karachi', label: 'Pakistan Standard Time (UTC+5:00)' },
  { value: 'Asia/Singapore', label: 'Singapore Standard Time (UTC+8:00)' },
  { value: 'Pacific/Guadalcanal', label: 'Solomon Islands Time (UTC+11:00)' },
  { value: 'Africa/Johannesburg', label: 'South Africa Standard Time (UTC+2:00)' },
  { value: 'Europe/London', label: 'United Kingdom / London Time (GMT/BST, UTC+0:00)' },
  { value: 'UTC', label: 'Universal Coordinated Time (UTC+0:00)' },
].sort((a, b) => a.label.localeCompare(b.label));

export default TIMEZONE_LIST;
